<?php /* @var $block \FasaPaymentSci\Fasapay\Block\Success */?>
<?php
if($block->getFasaMethod() == "fasapaymethod"){
	$block->getChangeStatusPayment();
	$fasa_put = $block->getOrder();
?>

<style>
	#fountainG{
	position:relative;
	width:234px;
	height:28px;
	margin:auto;
}
.fountainG{
	position:absolute;
	top:0;
	background-color:rgb(0,0,0);
	width:28px;
	height:28px;
	animation-name:bounce_fountainG;
		-o-animation-name:bounce_fountainG;
		-ms-animation-name:bounce_fountainG;
		-webkit-animation-name:bounce_fountainG;
		-moz-animation-name:bounce_fountainG;
	animation-duration:1.5s;
		-o-animation-duration:1.5s;
		-ms-animation-duration:1.5s;
		-webkit-animation-duration:1.5s;
		-moz-animation-duration:1.5s;
	animation-iteration-count:infinite;
		-o-animation-iteration-count:infinite;
		-ms-animation-iteration-count:infinite;
		-webkit-animation-iteration-count:infinite;
		-moz-animation-iteration-count:infinite;
	animation-direction:normal;
		-o-animation-direction:normal;
		-ms-animation-direction:normal;
		-webkit-animation-direction:normal;
		-moz-animation-direction:normal;
	transform:scale(.3);
		-o-transform:scale(.3);
		-ms-transform:scale(.3);
		-webkit-transform:scale(.3);
		-moz-transform:scale(.3);
	border-radius:19px;
		-o-border-radius:19px;
		-ms-border-radius:19px;
		-webkit-border-radius:19px;
		-moz-border-radius:19px;
}

#fountainG_1{
	left:0;
	animation-delay:0.6s;
		-o-animation-delay:0.6s;
		-ms-animation-delay:0.6s;
		-webkit-animation-delay:0.6s;
		-moz-animation-delay:0.6s;
}

#fountainG_2{
	left:29px;
	animation-delay:0.75s;
		-o-animation-delay:0.75s;
		-ms-animation-delay:0.75s;
		-webkit-animation-delay:0.75s;
		-moz-animation-delay:0.75s;
}

#fountainG_3{
	left:58px;
	animation-delay:0.9s;
		-o-animation-delay:0.9s;
		-ms-animation-delay:0.9s;
		-webkit-animation-delay:0.9s;
		-moz-animation-delay:0.9s;
}

#fountainG_4{
	left:88px;
	animation-delay:1.05s;
		-o-animation-delay:1.05s;
		-ms-animation-delay:1.05s;
		-webkit-animation-delay:1.05s;
		-moz-animation-delay:1.05s;
}

#fountainG_5{
	left:117px;
	animation-delay:1.2s;
		-o-animation-delay:1.2s;
		-ms-animation-delay:1.2s;
		-webkit-animation-delay:1.2s;
		-moz-animation-delay:1.2s;
}

#fountainG_6{
	left:146px;
	animation-delay:1.35s;
		-o-animation-delay:1.35s;
		-ms-animation-delay:1.35s;
		-webkit-animation-delay:1.35s;
		-moz-animation-delay:1.35s;
}

#fountainG_7{
	left:175px;
	animation-delay:1.5s;
		-o-animation-delay:1.5s;
		-ms-animation-delay:1.5s;
		-webkit-animation-delay:1.5s;
		-moz-animation-delay:1.5s;
}

#fountainG_8{
	left:205px;
	animation-delay:1.64s;
		-o-animation-delay:1.64s;
		-ms-animation-delay:1.64s;
		-webkit-animation-delay:1.64s;
		-moz-animation-delay:1.64s;
}



@keyframes bounce_fountainG{
	0%{
	transform:scale(1);
		background-color:rgb(0,0,0);
	}

	100%{
	transform:scale(.3);
		background-color:rgb(255,255,255);
	}
}

@-o-keyframes bounce_fountainG{
	0%{
	-o-transform:scale(1);
		background-color:rgb(0,0,0);
	}

	100%{
	-o-transform:scale(.3);
		background-color:rgb(255,255,255);
	}
}

@-ms-keyframes bounce_fountainG{
	0%{
	-ms-transform:scale(1);
		background-color:rgb(0,0,0);
	}

	100%{
	-ms-transform:scale(.3);
		background-color:rgb(255,255,255);
	}
}

@-webkit-keyframes bounce_fountainG{
	0%{
	-webkit-transform:scale(1);
		background-color:rgb(0,0,0);
	}

	100%{
	-webkit-transform:scale(.3);
		background-color:rgb(255,255,255);
	}
}

@-moz-keyframes bounce_fountainG{
	0%{
	-moz-transform:scale(1);
		background-color:rgb(0,0,0);
	}

	100%{
	-moz-transform:scale(.3);
		background-color:rgb(255,255,255);
	}
}
</style>
<form id="fasapay_form" action="" method="POST">
				<input type="hidden" name="fp_acc" value="<?php echo $block->getFasaId();	?>" />
    			<input type="hidden" name="fp_store" value="<?php echo $block->getStoreName();	?>" />
    			<input type="hidden" name="fp_item" value="<?php echo $fasa_put['store_id']; ?>" />
    			<input type="hidden" name="fp_amnt" value="<?php echo $fasa_put['subtotal']; ?>" />
    			<input type="hidden" name="fp_currency" value="<?php echo $fasa_put['store_currency_code']; ?>" />
    			<input type="hidden" name="fp_fee_mode" value="FIR" />
    			<input type="hidden" name="fp_comments" value="Pembayaran menggunakan store variable" />
    			<input type="hidden" name="fp_merchant_ref" value="<?php echo $fasa_put['protect_code']; ?>" />
				<input type="hidden" name="fp_success_url" value="http://<?php echo $_SERVER['SERVER_NAME'];?>/fasapay?pages=success" />
				<input type="hidden" name="fp_success_method" value="POST" />
				<input type="hidden" name="fp_fail_url" value="http://<?php echo $_SERVER['SERVER_NAME'];?>/fasapay?pages=failed" />
				<input type="hidden" name="fp_fail_method" value="POST" />
				<input type="hidden" name="fp_status_url" value="http://<?php echo $_SERVER['SERVER_NAME'];?>/fasapay?pages=status" />
				<input type="hidden" name="fp_status_method" value="POST" />
    			<input type="hidden" name="order_id" value="<?php echo $fasa_put['increment_id']; ?>" />
</form>
<input type="hidden" id="fasa_mode" value="<?php echo $block->getMode();?>" />
<hr>
<div id="yyy">
	<button onclick="next_fasapayment()" type="button" class="btn btn-primary">Continue payment</button>
</div>
<div id="xxx" style="display:none;">
<div id="fountainG">
	<div id="fountainG_1" class="fountainG"></div>
	<div id="fountainG_2" class="fountainG"></div>
	<div id="fountainG_3" class="fountainG"></div>
	<div id="fountainG_4" class="fountainG"></div>
	<div id="fountainG_5" class="fountainG"></div>
	<div id="fountainG_6" class="fountainG"></div>
	<div id="fountainG_7" class="fountainG"></div>
	<div id="fountainG_8" class="fountainG"></div>
</div>
</div>
<hr>
<script>
	function next_fasapayment(){
		var fasa_url;
		if(document.getElementById("fasa_mode").value === "Facom"){
			fasa_url = "https://sci.fasapay.com/";
		}else if(document.getElementById("fasa_mode").value === "Faid"){
			fasa_url = "https://fasapay.co.id/sci";
		}else if(document.getElementById("fasa_mode").value === "Sandbox"){
			fasa_url = "https://sandbox.fasapay.com/sci/";
		}
		var x = document.getElementById("xxx");
        var y = document.getElementById("yyy");
        x.style.display = "block";
        y.style.display = "none";
		window.setTimeout(function () {
			document.getElementById("fasapay_form").action = fasa_url;
            document.getElementById("fasapay_form").submit();
        }, 5000);
	}
</script>
<?php
	}
?>